# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
